{
 "title": "Owlet Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heart Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  hr AS \"Heart Rate\",\n  Serial AS \"Device\"\nFROM Vitals\nWHERE\n  $__timeFilter(\"ts\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "O2 Saturation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  ox AS \"Oxygenation\",\n  Serial AS \"Device\"\nFROM Vitals\nWHERE\n  $__timeFilter(\"ts\")\n  AND Serial IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sock Charge",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"ts\" AS \"time\",\n  bat\nFROM vitals\nWHERE\n  $__timeFilter(\"ts\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Movement",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"ts\" AS \"time\",\n  mv,\n  Serial AS \"Device\"\nFROM vitals\nWHERE\n  $__timeFilter(\"ts\")\n  AND Serial IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  hr AS \"Heart Rate\",\n  Serial AS \"Device\"\nFROM Vitals\nWHERE\n  $__timeFilter(\"ts\")\nAND chg != 1\nAND hr != 0\nAND Serial IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "O2 Saturation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  ox AS \"Oxygenation\",\n  Serial AS \"Device\"\nFROM vitals\nWHERE\n  $__timeFilter(\"ts\")\nAND ox != 0\nAND Serial is NOT NULL\nORDER BY 1"
    }
   ]
  }
 ]
}